### ISSUE TITLE
KeyError: 'videofront_xblock/translations'

### ISSUE THREAD

**Issue by muyouming** [regisb/videofront-xblock#1]
Hi:

I have install the open edx by the bitnami native installer. 
https://bitnami.com/redirect/to/193216/bitnami-edx-ginkgo.2-4-linux-x64-installer.run
when I followed the install guide to install this , 
my step:
1.  python -m pip install -e git+https://github.com/regisb/videofront-xblock.git@master#egg=videofront-xblock
2. there is an error in studio page saying not found the egg file, so I just git clone this repository and  moved the egg file to the right location.
cp /home/xxx/edx-ginkgo.2-4/videofront-xblock/dist/videofront_xblock-0.1-py2.7.egg /home/xxx/edx-ginkgo.2-4/apps/edx/venvs/edxapp/lib/python2.7/site-packages/videofront_xblock-0.1-py2.7.eg

3. add below  in "apps/edx/edx-platform/lms/envs/common.py"

```
> XBLOCK_SETTINGS = {
>         "videofront-xblock" : {
>                 'HOST': 'http://10.122.12.92:8000',
>                 'TOKEN': 'CHANGEME',
>         }
> }
```

4. add the module in the course advanced setting.
```
[
    "videofront-xblock"
]
```

after  that ,there is also an error in studio page 

![image](https://user-images.githubusercontent.com/12950114/40220023-525e174e-5aaa-11e8-8a16-97e941ab4f6a.png)

and the log is :
```

> 2018-05-18 02:34:43,548 INFO 22373 [tracking] logger.py:50 - {"username": "ituc", "event_type": "/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@5843b55378804c41bb527fe10a410982", "ip": "10.109.21.8", "agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3338.0 Safari/537.36", "host": "10.122.22.70", "referer": "http://10.122.22.70:18010/course/course-v1:edX+DemoX+Demo_Course", "accept_language": "en,zh-CN;q=0.9,zh;q=0.8", "event": "{\"POST\": {}, \"GET\": {\"action\": [\"new\"]}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@5843b55378804c41bb527fe10a410982"}, "time": "2018-05-18T06:34:43.547618+00:00", "page": null}
> 2018-05-18 02:34:44,587 INFO 22373 [tracking] logger.py:50 - {"username": "ituc", "event_type": "/xmodule/xmodule.js", "ip": "10.109.21.8", "agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3338.0 Safari/537.36", "host": "10.122.22.70", "referer": "http://10.122.22.70:18010/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@5843b55378804c41bb527fe10a410982?action=new", "accept_language": "en,zh-CN;q=0.9,zh;q=0.8", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/xmodule/xmodule.js"}, "time": "2018-05-18T06:34:44.587153+00:00", "page": null}
> 2018-05-18 02:34:44,809 INFO 22373 [tracking] logger.py:50 - {"username": "ituc", "event_type": "/xblock/block-v1:edX+DemoX+Demo_Course+type@vertical+block@5843b55378804c41bb527fe10a410982/container_preview", "ip": "10.109.21.8", "agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3338.0 Safari/537.36", "host": "10.122.22.70", "referer": "http://10.122.22.70:18010/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@5843b55378804c41bb527fe10a410982?action=new", "accept_language": "en,zh-CN;q=0.9,zh;q=0.8", "event": "{\"POST\": {}, \"GET\": {\"_\": [\"1526625259544\"]}}", "event_source": "server", "context": {"user_id": 2, "org_id": "", "course_id": "", "path": "/xblock/block-v1:edX+DemoX+Demo_Course+type@vertical+block@5843b55378804c41bb527fe10a410982/container_preview"}, "time": "2018-05-18T06:34:44.808949+00:00", "page": null}
> 2018-05-18 02:34:44,902 WARNING 22373 [contentstore.views.preview] preview.py:318 - Unable to render author_view for <VerticalBlockWithMixins @B084 visible_to_staff_only=False, graded=False, annotation_token_secret=u'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', hide_after_due=False, giturl=None, edxnotes=False, source_file=None, course_edit_method=u'Studio', default_tab=None, children=[BlockUsageLocator(CourseLocator(u'edX', u'DemoX', u'Demo_Course', None, None), u'videofront-xblock', u'f85ee662c3e2407189deaa336d356b5a')], in_entrance_exam=False, showanswer=u'attempted', display_name=u'Unit', video_speed_optimizations=True, graceperiod=datetime.timedelta(0, 18000), format=None, due=None, start=datetime.datetime(2013, 2, 5, 5, 0, tzinfo=tzutc()), xml_attributes={}, video_bumper={}, max_attempts=None, parent=BlockUsageLocator(CourseLocator(u'edX', u'DemoX', u'Demo_Course', None, None), u'sequential', u'4db931040f1240a0bb433a2bb70899b1'), tags=[], matlab_api_key=None, xqa_key=u'qaijS3UatK020Wc0sfCtFe0V6jpB4d64', is_entrance_exam=False, annotation_storage_url=u'http://your_annotation_storage.com', use_latex_compiler=False, days_early_for_beta=None, show_correctness=u'always', static_asset_path=u'', name=None, hide_from_toc=False, group_access={}, rerandomize=u'never', user_partitions=[], chrome=None, edxnotes_visibility=True, position=None, show_reset_button=False, self_paced=False>
> Traceback (most recent call last):
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/cms/djangoapps/contentstore/views/preview.py", line 316, in get_preview_fragment
>     fragment = module.render(preview_view, context)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/venvs/edxapp/lib/python2.7/site-packages/xblock/core.py", line 202, in render
>     return self.runtime.render(self, view, context)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1894, in render
>     return self.__getattr__('render')(block, view_name, context)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1302, in render
>     return super(MetricsMixin, self).render(block, view_name, context=context)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/venvs/edxapp/lib/python2.7/site-packages/xblock/runtime.py", line 808, in render
>     frag = view_fn(context)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/common/lib/xmodule/xmodule/vertical_block.py", line 99, in author_view
>     self.render_children(context, fragment, can_reorder=True, can_add=True)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/common/lib/xmodule/xmodule/studio_editable.py", line 26, in render_children
>     rendered_child = child.render(StudioEditableModule.get_preview_view_name(child), context)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/venvs/edxapp/lib/python2.7/site-packages/xblock/core.py", line 202, in render
>     return self.runtime.render(self, view, context)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1894, in render
>     return self.__getattr__('render')(block, view_name, context)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1302, in render
>     return super(MetricsMixin, self).render(block, view_name, context=context)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/venvs/edxapp/lib/python2.7/site-packages/xblock/runtime.py", line 812, in render
>     updated_frag = self.wrap_xblock(block, view_name, frag, context)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1254, in wrap_xblock
>     frag = wrapper(block, view, frag, context)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/cms/djangoapps/contentstore/views/preview.py", line 301, in _studio_wrap_xblock
>     html = render_to_string('studio_xblock_wrapper.html', template_context)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 188, in render_to_string
>     return template.render_unicode(**context_dictionary)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/venvs/edxapp/lib/python2.7/site-packages/mako/template.py", line 454, in render_unicode
>     as_unicode=True)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/venvs/edxapp/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
>     **_kwargs_for_callable(callable_, data))
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/venvs/edxapp/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
>     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/venvs/edxapp/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
>     callable_(context, *args, **kwargs)
>   File "/home/renss1/edx-ginkgo.2-4/.tmp/mako_cms/a27c6b3e8218a5517b2ed64b1cc50040/studio_xblock_wrapper.html.py", line 63, in render_body
>     messages = xblock.validate().to_json()
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/venvs/edxapp/lib/python2.7/site-packages/xblockutils/studio_editable.py", line 267, in validate
>     validation = super(StudioEditableXBlockMixin, self).validate()
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/lms/djangoapps/lms_xblock/mixin.py", line 149, in validate
>     _ = self.runtime.service(self, "i18n").ugettext
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1923, in service
>     service = self._module_system.service(block, service_name)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1842, in service
>     return service(block)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 384, in __init__
>     xblock_locale_path = resource_filename(xblock_resource, xblock_locale_dir)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/venvs/edxapp/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1203, in resource_filename
>     self, resource_name
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/venvs/edxapp/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1716, in get_resource_filename
>     return self._extract_resource(manager, zip_path)
>   File "/home/renss1/edx-ginkgo.2-4/apps/edx/venvs/edxapp/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1737, in _extract_resource
>     timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
> KeyError: 'videofront_xblock/translations'

```

Could someone help? thanks.

**Comment by muyouming** [comment]
when I reinstalled edx and this xblock ,issue fixed.

**Comment by regisb** [comment]
Awesome! I love it when issues get magically solved ;)
